Repository Asset-management-service/backend, pull requests merged in 2022-04, with the labels that each got.

#21 [Refactor] jwt + oauth + spring security conflicts 해결
  build.gradle
  src/main/java/com/backend/moamoa/MoamoaApplication.java
  src/main/java/com/backend/moamoa/domain/post/entity/Comment.java
  src/main/java/com/backend/moamoa/domain/post/entity/Post.java
  src/main/java/com/backend/moamoa/domain/post/service/PostService.java
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/domain/user/entity/User.java
  src/main/java/com/backend/moamoa/domain/user/entity/UserRefreshToken.java
  src/main/java/com/backend/moamoa/domain/user/oauth/controller/AuthController.java
  src/main/java/com/backend/moamoa/domain/user/oauth/entity/CustomUserDetails.java
  src/main/java/com/backend/moamoa/domain/user/oauth/entity/ProviderType.java
  src/main/java/com/backend/moamoa/domain/user/oauth/exception/OAuthProviderMissMatchException.java
  src/main/java/com/backend/moamoa/domain/user/oauth/exception/RestAuthenticationEntryPoint.java
  src/main/java/com/backend/moamoa/domain/user/oauth/exception/TokenValidFailedException.java
  src/main/java/com/backend/moamoa/domain/user/oauth/filter/JwtFilter.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/TokenAccessDeniedHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/OAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/impl/NaverOAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/provider/AuthToken.java
  src/main/java/com/backend/moamoa/domain/user/oauth/provider/AuthTokenProvider.java
  src/main/java/com/backend/moamoa/domain/user/oauth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomUserDetailsService.java
  src/main/java/com/backend/moamoa/domain/user/repository/UserRefreshTokenRepository.java
  src/main/java/com/backend/moamoa/domain/user/repository/UserRepository.java
  src/main/java/com/backend/moamoa/domain/user/service/UserService.java
  src/main/java/com/backend/moamoa/global/bean/swagger/SwaggerConfiguration.java
  src/main/java/com/backend/moamoa/global/common/ApiResponse.java
  src/main/java/com/backend/moamoa/global/common/ApiResponseHeader.java
  src/main/java/com/backend/moamoa/global/config/AppConfig.java
  src/main/java/com/backend/moamoa/global/config/AppProperties.java
  src/main/java/com/backend/moamoa/global/config/CorsProperties.java
  src/main/java/com/backend/moamoa/global/config/JwtConfig.java
  src/main/java/com/backend/moamoa/global/config/SecurityConfig.java
  src/main/java/com/backend/moamoa/global/utils/CookieUtil.java
  src/main/resources/application.yml
Labels: ✨ Feature, 📬 API

#22 [Refactor] 전반적인 코드 리팩토링 및 개인정보 변경 API 추가
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/backend/moamoa/domain/user/dto/response/UserResponse.java
  src/main/java/com/backend/moamoa/domain/user/entity/User.java
  src/main/java/com/backend/moamoa/domain/user/oauth/controller/AuthController.java
  src/main/java/com/backend/moamoa/domain/user/oauth/entity/CustomUserDetails.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/TokenAccessDeniedHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/OAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/OAuth2UserInfoFactory.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/impl/GoogleOAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/impl/KakaoOAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/info/impl/NaverOAuth2UserInfo.java
  src/main/java/com/backend/moamoa/domain/user/oauth/provider/AuthToken.java
  src/main/java/com/backend/moamoa/domain/user/oauth/provider/AuthTokenProvider.java
  src/main/java/com/backend/moamoa/domain/user/oauth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomUserDetailsService.java
  src/main/java/com/backend/moamoa/domain/user/repository/UserRefreshTokenRepository.java
  src/main/java/com/backend/moamoa/domain/user/repository/UserRepository.java
  src/main/java/com/backend/moamoa/domain/user/service/UserService.java
  src/main/java/com/backend/moamoa/global/config/AppConfig.java
  src/main/java/com/backend/moamoa/global/config/AppProperties.java
  src/main/java/com/backend/moamoa/global/config/CorsProperties.java
  src/main/java/com/backend/moamoa/global/config/SecurityConfig.java
  src/main/java/com/backend/moamoa/global/utils/SecurityUtil.java
  src/main/java/com/backend/moamoa/global/utils/UserUtil.java
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#24 [Feat] 배포를 위한 설정 파일 변경
  src/main/java/com/backend/moamoa/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: 🌏 Deploy

#28 [Feat] 이메일 인증 API 추가 및 Swagger Ui 설명, SecurityConfig 변경
  .gitignore
  build.gradle
  src/main/java/com/backend/moamoa/domain/user/config/MailAuthConfig.java
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/domain/user/dto/request/UserEmailRequest.java
  src/main/java/com/backend/moamoa/domain/user/dto/request/UserUpdateRequest.java
  src/main/java/com/backend/moamoa/domain/user/dto/response/UserResponse.java
  src/main/java/com/backend/moamoa/domain/user/entity/User.java
  src/main/java/com/backend/moamoa/domain/user/entity/UserMailAuth.java
  src/main/java/com/backend/moamoa/domain/user/repository/MailAuthRepository.java
  src/main/java/com/backend/moamoa/domain/user/repository/UserRepository.java
  src/main/java/com/backend/moamoa/domain/user/service/MailSendService.java
  src/main/java/com/backend/moamoa/domain/user/service/UserService.java
  src/main/java/com/backend/moamoa/domain/user/utils/MailUtils.java
  src/main/java/com/backend/moamoa/domain/user/utils/TempKey.java
  src/main/java/com/backend/moamoa/global/common/ApiResponse.java
  src/main/java/com/backend/moamoa/global/config/AmazonS3Config.java
  src/main/java/com/backend/moamoa/global/config/SecurityConfig.java
  src/main/java/com/backend/moamoa/global/exception/ErrorCode.java
  src/main/java/com/backend/moamoa/global/s3/S3Controller.java
  src/main/java/com/backend/moamoa/global/s3/S3Uploader.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
Labels: 🔨 Refactor, 📬 API, 📃 Docs

#32 Fix : GitIgnore 설정
  src/main/java/com/backend/moamoa/domain/asset/moneylog/entity/MoneyLog.java
  src/main/java/com/backend/moamoa/domain/asset/salary/controller/SalaryController.java
  src/main/java/com/backend/moamoa/domain/asset/salary/dto/FixedCostDto.java
  src/main/java/com/backend/moamoa/domain/asset/salary/dto/SalaryRequest.java
  src/main/java/com/backend/moamoa/domain/asset/salary/dto/SalaryResponse.java
  src/main/java/com/backend/moamoa/domain/asset/salary/dto/VariableCostDto.java
  src/main/java/com/backend/moamoa/domain/asset/salary/entity/Category.java
  src/main/java/com/backend/moamoa/domain/asset/salary/entity/CostType.java
  src/main/java/com/backend/moamoa/domain/asset/salary/entity/Salary.java
  src/main/java/com/backend/moamoa/domain/asset/salary/repository/CategoryRepository.java
  src/main/java/com/backend/moamoa/domain/asset/salary/repository/SalaryRepository.java
  src/main/java/com/backend/moamoa/domain/asset/salary/service/SalaryService.java
  src/main/resources/application-aws.yml
  src/main/resources/application.yml
Labels: 🐞 BugFix

#35 Refactor : 게시글 하나 조회시 N+1 문제 해결 및 반환타입 요구사항 수정 완료
  src/main/java/com/backend/moamoa/domain/post/controller/PostController.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/CommentsChildrenResponse.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/PostCreateResponse.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/PostOneCommentResponse.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/PostOneResponse.java
  src/main/java/com/backend/moamoa/domain/post/repository/comment/CommentCustomRepository.java
  src/main/java/com/backend/moamoa/domain/post/repository/comment/CommentRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/post/repository/post/PostCustomRepository.java
  src/main/java/com/backend/moamoa/domain/post/repository/post/PostRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/post/service/CommentService.java
  src/main/java/com/backend/moamoa/domain/post/service/PostService.java
  src/main/java/com/backend/moamoa/global/exception/CustomException.java
  src/main/java/com/backend/moamoa/global/exception/ErrorResponse.java
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API

#36 [Refactor] 리프레시 토큰 redis 저장 로직 추가 & 토큰 재발급 API 리팩터링
  src/main/java/com/backend/moamoa/domain/post/repository/comment/CommentRepository.java
  src/main/java/com/backend/moamoa/domain/post/repository/post/PostRepository.java
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/domain/user/dto/response/MyCommentResponse.java
  src/main/java/com/backend/moamoa/domain/user/dto/response/MyPostResponse.java
  src/main/java/com/backend/moamoa/domain/user/entity/User.java
  src/main/java/com/backend/moamoa/domain/user/entity/UserRefreshToken.java
  src/main/java/com/backend/moamoa/domain/user/oauth/controller/AuthController.java
  src/main/java/com/backend/moamoa/domain/user/oauth/dto/request/TokenRequest.java
  src/main/java/com/backend/moamoa/domain/user/oauth/dto/response/TokenResponse.java
  src/main/java/com/backend/moamoa/domain/user/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/backend/moamoa/domain/user/oauth/provider/AuthToken.java
  src/main/java/com/backend/moamoa/domain/user/oauth/provider/AuthTokenProvider.java
  src/main/java/com/backend/moamoa/domain/user/oauth/repository/OAuth2AuthorizationRequestBasedOnCookieRepository.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/AuthService.java
  src/main/java/com/backend/moamoa/domain/user/repository/UserRefreshTokenRepository.java
  src/main/java/com/backend/moamoa/domain/user/service/UserService.java
  src/main/java/com/backend/moamoa/global/bean/swagger/SwaggerConfiguration.java
  src/main/java/com/backend/moamoa/global/config/RedisRepositoryConfig.java
  src/main/java/com/backend/moamoa/global/config/SecurityConfig.java
  src/main/java/com/backend/moamoa/global/exception/ErrorCode.java
  src/main/java/com/backend/moamoa/global/exception/ErrorResponse.java
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#40 Feat : 가계부 엔티티 설계 및 기본 구조 설계
  build.gradle
  src/main/java/com/backend/moamoa/domain/asset/controller/AssetController.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/AssetCategoryRequest.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/BudgetRequest.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/CreateRevenueExpenditureRequest.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/ExpenditureRequest.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/AssetCategoriesResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/AssetCategoryResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/CreateBudgetResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/CreateExpenditureResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/CreateRevenueExpenditureResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/RevenueExpenditureResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/RevenueExpenditureSumResponse.java
  src/main/java/com/backend/moamoa/domain/asset/entity/AssetCategory.java
  src/main/java/com/backend/moamoa/domain/asset/entity/AssetCategoryType.java
  src/main/java/com/backend/moamoa/domain/asset/entity/Budget.java
  src/main/java/com/backend/moamoa/domain/asset/entity/ExpenditureRatio.java
  src/main/java/com/backend/moamoa/domain/asset/entity/RevenueExpenditure.java
  src/main/java/com/backend/moamoa/domain/asset/entity/RevenueExpenditureType.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetCategoryRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetCategoryRepositoryCustom.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetCategoryRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/asset/repository/BudgetRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/ExpenditureRatioRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/RevenueExpenditureRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/RevenueExpenditureRepositoryCustom.java
  src/main/java/com/backend/moamoa/domain/asset/repository/RevenueExpenditureRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/asset/service/AssetService.java
  src/main/java/com/backend/moamoa/domain/post/controller/CommentController.java
  src/main/java/com/backend/moamoa/domain/post/controller/PostController.java
  src/main/java/com/backend/moamoa/domain/post/dto/request/PostRequest.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/CommentResponse.java
  src/main/java/com/backend/moamoa/domain/post/service/CommentService.java
  src/main/java/com/backend/moamoa/global/exception/ErrorCode.java
Labels: ✨ Feature, 🔨 Refactor, 📬 API, ⚙ Setting

#43 [Feat] 마이 페이지 내가 스크랩한 글 보기 API 추가
  src/main/java/com/backend/moamoa/domain/post/repository/post/ScrapRepository.java
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/domain/user/dto/response/MyScrapResponse.java
  src/main/java/com/backend/moamoa/domain/user/service/UserService.java
Labels: 📬 API

#44 Refactor : 게시글 단건 조회시 이미지 경로 반환 + user를 검증하는 부분 리팩토링
  src/main/java/com/backend/moamoa/domain/asset/service/AssetService.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/PostOneResponse.java
  src/main/java/com/backend/moamoa/domain/post/repository/post/PostRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/post/service/CommentService.java
  src/main/java/com/backend/moamoa/domain/post/service/PostService.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomUserDetailsService.java
Labels: 🐞 BugFix, 🔨 Refactor, 🥰 Accessibility, 🙋‍♂️ Question

#45 Fix : 게시글 조회시 myLike, myScrap 오작동 및 댓글 수정, 삭제 시 권한 오류 수정
  src/main/java/com/backend/moamoa/domain/post/controller/CommentController.java
  src/main/java/com/backend/moamoa/domain/post/repository/comment/CommentRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/post/repository/post/PostRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomOAuth2UserService.java
Labels: 🐞 BugFix, 🔨 Refactor

#46 Refactor : 회원가입 시 디폴트 카테고리 생성
  src/main/java/com/backend/moamoa/domain/user/oauth/service/CustomOAuth2UserService.java
Labels: 🔨 Refactor

#47 [Feat] 결산 API 추가
  src/main/java/com/backend/moamoa/domain/asset/dto/response/RevenueExpenditureResponse.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetCategoryRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetCategoryRepositoryCustom.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetCategoryRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/asset/repository/ExpenditureRatioRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/RevenueExpenditureRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/RevenueExpenditureRepositoryCustom.java
  src/main/java/com/backend/moamoa/domain/asset/repository/RevenueExpenditureRepositoryImpl.java
  src/main/java/com/backend/moamoa/domain/settlement/controller/SettlementController.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/CostResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/MonthResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/RevenueResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/TotalResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/WeekResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/settle/MonthSettleResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/settle/WeekSettleResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/settle/YearSettleResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/total/ComparisonResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/total/ComparisonsResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/total/TotalComparisonResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/service/SettlementService.java
  src/main/java/com/backend/moamoa/global/exception/ErrorCode.java
Labels: ✨ Feature, 📬 API

#48 Refactor : 지출비율 설정, 예산설정 Http 메소드 변경
  src/main/java/com/backend/moamoa/domain/asset/controller/AssetController.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/ExpenditureRequest.java
  src/main/java/com/backend/moamoa/domain/asset/entity/Budget.java
  src/main/java/com/backend/moamoa/domain/asset/entity/ExpenditureRatio.java
  src/main/java/com/backend/moamoa/domain/asset/repository/BudgetRepository.java
  src/main/java/com/backend/moamoa/domain/asset/service/AssetService.java
  src/test/java/com/backend/moamoa/MoamoaApplicationTests.java
Labels: 🔨 Refactor, 📬 API

#50 Feat : 머니로그 테이블 설계 및 간단한 작성 API
  src/main/java/com/backend/moamoa/domain/asset/controller/AssetController.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/CreateAssetGoalRequest.java
  src/main/java/com/backend/moamoa/domain/asset/dto/request/CreateMoneyLogRequest.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/CreateAssetGoalResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/CreateMoneyLogResponse.java
  src/main/java/com/backend/moamoa/domain/asset/entity/AssetGoal.java
  src/main/java/com/backend/moamoa/domain/asset/entity/MoneyLog.java
  src/main/java/com/backend/moamoa/domain/asset/repository/AssetGoalRepository.java
  src/main/java/com/backend/moamoa/domain/asset/repository/MoneyLogRepository.java
  src/main/java/com/backend/moamoa/domain/asset/service/AssetService.java
  src/main/java/com/backend/moamoa/domain/post/entity/PostImage.java
  src/main/java/com/backend/moamoa/global/exception/ErrorCode.java
Labels: ✨ Feature, 📬 API

#55 [Refactor] 로그아웃 API 스프링 시큐리티 예외 설정
  src/main/java/com/backend/moamoa/global/bean/security/SecurityConfig.java
Labels: 🥰 Accessibility, 📬 API

#57 [Refactor] 결산 API 리팩토링 및 이메일 인증 시큐리티 예외 설정
  src/main/java/com/backend/moamoa/domain/settlement/controller/SettlementController.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/CostResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/MonthResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/TotalResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/WeekResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/settle/WeekSettleResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/dto/response/total/ComparisonsResponse.java
  src/main/java/com/backend/moamoa/domain/settlement/service/SettlementService.java
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/global/bean/security/SecurityConfig.java
  src/main/java/com/backend/moamoa/global/s3/S3Uploader.java
Labels: 🥰 Accessibility, 📬 API

#58 Refactor : 머니로그 공유 시 게시글 생성 로직 추가 및 변경
  src/main/java/com/backend/moamoa/domain/asset/entity/AssetCategory.java
  src/main/java/com/backend/moamoa/domain/asset/entity/Budget.java
  src/main/java/com/backend/moamoa/domain/post/dto/request/PostRequest.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/PostCreateResponse.java
  src/main/java/com/backend/moamoa/domain/post/service/PostService.java
Labels: 🔨 Refactor, 📬 API

#60 Refactor : 컨트롤러 코드 스타일 통일 및 반환 상태 변경!
  src/main/java/com/backend/moamoa/domain/asset/controller/AssetController.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/AssetCategoryDtoResponse.java
  src/main/java/com/backend/moamoa/domain/asset/dto/response/ExpenditureResponse.java
  src/main/java/com/backend/moamoa/domain/asset/service/AssetService.java
  src/main/java/com/backend/moamoa/domain/post/controller/CommentController.java
  src/main/java/com/backend/moamoa/domain/post/controller/PostController.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/CommentDeleteResponse.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/PostUpdateResponse.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/ScrapResponse.java
  src/main/java/com/backend/moamoa/domain/post/dto/response/UpdateCommentResponse.java
  src/main/java/com/backend/moamoa/domain/post/service/CommentService.java
  src/main/java/com/backend/moamoa/domain/post/service/PostService.java
Labels: 🔨 Refactor

#61 [Refactor] 전반적인 코드 스타일 변경 및 유저 API 리팩토링
  src/main/java/com/backend/moamoa/domain/user/controller/AuthController.java
  src/main/java/com/backend/moamoa/domain/user/controller/UserController.java
  src/main/java/com/backend/moamoa/domain/user/dto/response/ReissueResponse.java
  src/main/java/com/backend/moamoa/domain/user/entity/User.java
  src/main/java/com/backend/moamoa/domain/user/service/AuthService.java
  src/main/java/com/backend/moamoa/domain/user/service/MailSendService.java
  src/main/java/com/backend/moamoa/domain/user/service/UserService.java
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API
